export enum InventoryMovementType {
  ENTRY = 'ENTRY',
  EXIT = 'EXIT',
  ADJUSTMENT_INCREASE = 'ADJUSTMENT_INCREASE',
  ADJUSTMENT_DECREASE = 'ADJUSTMENT_DECREASE',
  RESERVATION = 'RESERVATION',
  RESERVATION_CANCELED = 'RESERVATION_CANCELED',
  SALE_COMPLETED = 'SALE_COMPLETED',
  SALE_CANCELED_REVERSAL = 'SALE_CANCELED_REVERSAL',
}
export enum InventoryReservationStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
  EXPIRED = 'EXPIRED',
}
export enum InventoryReferenceType {
  MANUAL = 'MANUAL',
  SALE = 'SALE',
  ORDER = 'ORDER',
  INVENTORY_COUNT = 'INVENTORY_COUNT',
  IMPORT = 'IMPORT',
  SYSTEM = 'SYSTEM',
}
