export enum OrderSource {
  MARKETPLACE = 'MARKETPLACE',
  MANUAL = 'MANUAL',
  OWN_STORE = 'OWN_STORE',
  IMPORT = 'IMPORT',
  API = 'API',
}
export enum OrderStatus {
  NEW = 'NEW',
  PAID = 'PAID',
  AWAITING_INVOICE = 'AWAITING_INVOICE',
  INVOICED = 'INVOICED',
  READY_TO_SHIP = 'READY_TO_SHIP',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELED = 'CANCELED',
  ERROR = 'ERROR',
}
export enum PaymentStatus {
  PENDING = 'PENDING',
  AUTHORIZED = 'AUTHORIZED',
  PAID = 'PAID',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  CANCELED = 'CANCELED',
  REJECTED = 'REJECTED',
  CHARGEBACK = 'CHARGEBACK',
  UNKNOWN = 'UNKNOWN',
}
export enum ShippingStatus {
  NOT_REQUIRED = 'NOT_REQUIRED',
  PENDING = 'PENDING',
  READY_TO_SHIP = 'READY_TO_SHIP',
  SHIPPED = 'SHIPPED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
  RETURNING = 'RETURNING',
  RETURNED = 'RETURNED',
  CANCELED = 'CANCELED',
  UNKNOWN = 'UNKNOWN',
}
export enum FiscalStatus {
  NOT_ISSUED = 'NOT_ISSUED',
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  AUTHORIZED = 'AUTHORIZED',
  REJECTED = 'REJECTED',
  CANCELED = 'CANCELED',
  ERROR = 'ERROR',
}
export enum CommissionStatus {
  CONFIRMED = 'CONFIRMED',
  ESTIMATED = 'ESTIMATED',
  NOT_AVAILABLE = 'NOT_AVAILABLE',
}
export enum DocumentType {
  CPF = 'CPF',
  CNPJ = 'CNPJ',
  OTHER = 'OTHER',
  UNKNOWN = 'UNKNOWN',
}
export enum OrderAddressType {
  SHIPPING = 'SHIPPING',
  BILLING = 'BILLING',
}
export enum PaymentMethod {
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  PIX = 'PIX',
  BOLETO = 'BOLETO',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CASH = 'CASH',
  WALLET = 'WALLET',
  MARKETPLACE_BALANCE = 'MARKETPLACE_BALANCE',
  OTHER = 'OTHER',
  UNKNOWN = 'UNKNOWN',
}
export enum OrderIssueCode {
  PRODUCT_LINK_MISSING = 'PRODUCT_LINK_MISSING',
  PRODUCT_INACTIVE = 'PRODUCT_INACTIVE',
  INVALID_QUANTITY = 'INVALID_QUANTITY',
  TOTAL_MISMATCH = 'TOTAL_MISMATCH',
  SHIPPING_DATA_MISSING = 'SHIPPING_DATA_MISSING',
  PAYMENT_DATA_MISSING = 'PAYMENT_DATA_MISSING',
  EXTERNAL_DATA_INCOMPLETE = 'EXTERNAL_DATA_INCOMPLETE',
  UNKNOWN_EXTERNAL_STATUS = 'UNKNOWN_EXTERNAL_STATUS',
}
export enum OrderIssueSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
}
export enum OrderIssueStatus {
  OPEN = 'OPEN',
  RESOLVED = 'RESOLVED',
  IGNORED = 'IGNORED',
}
export enum OrderHistorySource {
  USER = 'USER',
  MARKETPLACE = 'MARKETPLACE',
  SYSTEM = 'SYSTEM',
  PAYMENT = 'PAYMENT',
  SHIPPING = 'SHIPPING',
  FISCAL = 'FISCAL',
  IMPORT = 'IMPORT',
  REPROCESSING = 'REPROCESSING',
}
