export enum SalesChannelCode {
  MERCADO_LIVRE = 'MERCADO_LIVRE',
  SHOPEE = 'SHOPEE',
  AMAZON = 'AMAZON',
  MAGALU = 'MAGALU',
  CUSTOM = 'CUSTOM',
  OWN_STORE = 'OWN_STORE',
  MANUAL = 'MANUAL',
}
export enum SalesChannelType {
  MARKETPLACE = 'MARKETPLACE',
  ECOMMERCE = 'ECOMMERCE',
  MANUAL = 'MANUAL',
  CUSTOM = 'CUSTOM',
}
export enum SalesChannelConnectionStatus {
  PENDING = 'PENDING',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  REAUTH_REQUIRED = 'REAUTH_REQUIRED',
  ERROR = 'ERROR',
  DISCONNECTED = 'DISCONNECTED',
  DISABLED = 'DISABLED',
}
