import { MigrationInterface, QueryRunner } from 'typeorm';
export class CreateSalesChannels1723766900000 implements MigrationInterface {
  async up(q: QueryRunner) {
    await q.query(`CREATE TYPE "sales_channels_code_enum" AS ENUM('MERCADO_LIVRE','SHOPEE','AMAZON','MAGALU','CUSTOM','OWN_STORE','MANUAL')`);
    await q.query(`CREATE TYPE "sales_channels_type_enum" AS ENUM('MARKETPLACE','ECOMMERCE','MANUAL','CUSTOM')`);
    await q.query(`CREATE TYPE "sales_channel_connections_status_enum" AS ENUM('PENDING','ACTIVE','DISABLED','ERROR','TOKEN_EXPIRED','REAUTH_REQUIRED','DISCONNECTED')`);
    await q.query(`CREATE TABLE "sales_channels"("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,"code" "sales_channels_code_enum" UNIQUE NOT NULL,"name" varchar(100) NOT NULL,"type" "sales_channels_type_enum" NOT NULL,"description" text,"icon_key" varchar(60),"supports_oauth" boolean DEFAULT false NOT NULL,"supports_products" boolean DEFAULT false NOT NULL,"supports_orders" boolean DEFAULT false NOT NULL,"supports_stock" boolean DEFAULT false NOT NULL,"supports_prices" boolean DEFAULT false NOT NULL,"supports_invoices" boolean DEFAULT false NOT NULL,"is_active" boolean DEFAULT true NOT NULL,"configuration_schema" jsonb,"created_at" timestamp DEFAULT now() NOT NULL,"updated_at" timestamp DEFAULT now() NOT NULL)`);
    await q.query(`CREATE TABLE "sales_channel_connections"("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,"company_id" uuid NOT NULL REFERENCES "companies"("id") ON DELETE CASCADE,"sales_channel_id" uuid NOT NULL REFERENCES "sales_channels"("id"),"display_name" varchar(140) NOT NULL,"external_account_id" varchar(160),"external_account_name" varchar(180),"status" "sales_channel_connections_status_enum" DEFAULT 'PENDING' NOT NULL,"connected_at" timestamptz,"disconnected_at" timestamptz,"token_expires_at" timestamptz,"granted_scopes" jsonb DEFAULT '[]'::jsonb NOT NULL,"last_sync_at" timestamptz,"last_successful_sync_at" timestamptz,"last_error_at" timestamptz,"last_error_code" varchar(80),"last_error_message" varchar(500),"metadata" jsonb,"created_by_user_id" uuid NOT NULL REFERENCES "users"("id"),"updated_by_user_id" uuid REFERENCES "users"("id") ON DELETE SET NULL,"created_at" timestamp DEFAULT now() NOT NULL,"updated_at" timestamp DEFAULT now() NOT NULL)`);
    await q.query(`CREATE INDEX "IDX_sales_channel_connections_company_channel" ON "sales_channel_connections"("company_id","sales_channel_id")`);
    await q.query(`CREATE UNIQUE INDEX "UQ_scc_active_external_account" ON "sales_channel_connections"("company_id","sales_channel_id","external_account_id") WHERE "external_account_id" IS NOT NULL AND "status" <> 'DISCONNECTED'`);
    await q.query(`CREATE TABLE "sales_channel_credentials"("id" uuid DEFAULT gen_random_uuid() PRIMARY KEY,"company_id" uuid NOT NULL REFERENCES "companies"("id") ON DELETE CASCADE,"connection_id" uuid UNIQUE NOT NULL REFERENCES "sales_channel_connections"("id") ON DELETE CASCADE,"encrypted_access_token" text,"access_token_iv" varchar,"access_token_auth_tag" varchar,"encrypted_refresh_token" text,"refresh_token_iv" varchar,"refresh_token_auth_tag" varchar,"encryption_key_version" varchar NOT NULL,"created_at" timestamp DEFAULT now() NOT NULL,"updated_at" timestamp DEFAULT now() NOT NULL)`);
  }
  async down(q: QueryRunner) {
    await q.query('DROP TABLE "sales_channel_credentials"'); await q.query('DROP TABLE "sales_channel_connections"'); await q.query('DROP TABLE "sales_channels"');
    await q.query('DROP TYPE "sales_channel_connections_status_enum"'); await q.query('DROP TYPE "sales_channels_type_enum"'); await q.query('DROP TYPE "sales_channels_code_enum"');
  }
}
