import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateOrders1723767300000 implements MigrationInterface {
  name = 'CreateOrders1723767300000';
  async up(q: QueryRunner): Promise<void> {
    await q.query(
      `CREATE TYPE order_source_enum AS ENUM ('MARKETPLACE','MANUAL','OWN_STORE','IMPORT','API'); CREATE TYPE order_status_enum AS ENUM ('NEW','PAID','AWAITING_INVOICE','INVOICED','READY_TO_SHIP','SHIPPED','DELIVERED','CANCELED','ERROR'); CREATE TYPE payment_status_enum AS ENUM ('PENDING','AUTHORIZED','PAID','PARTIALLY_PAID','REFUNDED','PARTIALLY_REFUNDED','CANCELED','REJECTED','CHARGEBACK','UNKNOWN'); CREATE TYPE shipping_status_enum AS ENUM ('NOT_REQUIRED','PENDING','READY_TO_SHIP','SHIPPED','IN_TRANSIT','DELIVERED','DELIVERY_FAILED','RETURNING','RETURNED','CANCELED','UNKNOWN'); CREATE TYPE fiscal_status_enum AS ENUM ('NOT_ISSUED','PENDING','PROCESSING','AUTHORIZED','REJECTED','CANCELED','ERROR'); CREATE TYPE commission_status_enum AS ENUM ('CONFIRMED','ESTIMATED','NOT_AVAILABLE'); CREATE TYPE document_type_enum AS ENUM ('CPF','CNPJ','OTHER','UNKNOWN'); CREATE TYPE order_address_type_enum AS ENUM ('SHIPPING','BILLING'); CREATE TYPE payment_method_enum AS ENUM ('CREDIT_CARD','DEBIT_CARD','PIX','BOLETO','BANK_TRANSFER','CASH','WALLET','MARKETPLACE_BALANCE','OTHER','UNKNOWN'); CREATE TYPE order_issue_code_enum AS ENUM ('PRODUCT_LINK_MISSING','PRODUCT_INACTIVE','INVALID_QUANTITY','TOTAL_MISMATCH','SHIPPING_DATA_MISSING','PAYMENT_DATA_MISSING','EXTERNAL_DATA_INCOMPLETE','UNKNOWN_EXTERNAL_STATUS'); CREATE TYPE order_issue_severity_enum AS ENUM ('INFO','WARNING','ERROR'); CREATE TYPE order_issue_status_enum AS ENUM ('OPEN','RESOLVED','IGNORED'); CREATE TYPE order_history_source_enum AS ENUM ('USER','MARKETPLACE','SYSTEM','PAYMENT','SHIPPING','FISCAL','IMPORT','REPROCESSING')`,
    );
    await q.query(
      `CREATE TABLE company_order_sequences(company_id uuid PRIMARY KEY REFERENCES companies(id) ON DELETE RESTRICT,next_number bigint NOT NULL CHECK(next_number>0),updated_at timestamptz NOT NULL DEFAULT now())`,
    );
    await q.query(
      `CREATE TABLE orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,internal_number bigint NOT NULL,source order_source_enum NOT NULL,sales_channel_id uuid REFERENCES sales_channels(id) ON DELETE RESTRICT,sales_channel_connection_id uuid REFERENCES sales_channel_connections(id) ON DELETE RESTRICT,marketplace_order_import_id uuid REFERENCES marketplace_order_imports(id) ON DELETE RESTRICT,external_order_id varchar(100),external_order_number varchar(100),status order_status_enum NOT NULL,payment_status payment_status_enum NOT NULL,shipping_status shipping_status_enum NOT NULL,fiscal_status fiscal_status_enum NOT NULL,external_status varchar(80),external_payment_status varchar(80),external_shipping_status varchar(80),currency varchar(3) NOT NULL,items_subtotal numeric(15,2) NOT NULL CHECK(items_subtotal>=0),shipping_amount numeric(15,2) NOT NULL CHECK(shipping_amount>=0),discount_amount numeric(15,2) NOT NULL CHECK(discount_amount>=0),commission_amount numeric(15,2),commission_status commission_status_enum NOT NULL,other_fees_amount numeric(15,2) NOT NULL CHECK(other_fees_amount>=0),total_amount numeric(15,2) NOT NULL CHECK(total_amount>=0),paid_amount numeric(15,2) NOT NULL CHECK(paid_amount>=0),refunded_amount numeric(15,2) NOT NULL CHECK(refunded_amount>=0),notes text,error_code varchar(80),error_message varchar(500),purchased_at timestamptz,paid_at timestamptz,invoiced_at timestamptz,ready_to_ship_at timestamptz,shipped_at timestamptz,delivered_at timestamptz,canceled_at timestamptz,external_created_at timestamptz,external_updated_at timestamptz,imported_at timestamptz,created_by_user_id uuid REFERENCES users(id) ON DELETE RESTRICT,updated_by_user_id uuid REFERENCES users(id) ON DELETE RESTRICT,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT uq_orders_company_number UNIQUE(company_id,internal_number))`,
    );
    await q.query(
      `CREATE UNIQUE INDEX uq_orders_external ON orders(company_id,sales_channel_connection_id,external_order_id) WHERE external_order_id IS NOT NULL; CREATE INDEX idx_orders_company_status ON orders(company_id,status); CREATE INDEX idx_orders_company_purchased ON orders(company_id,purchased_at DESC)`,
    );
    await q.query(
      `CREATE TABLE order_customers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,order_id uuid NOT NULL UNIQUE REFERENCES orders(id) ON DELETE RESTRICT,external_customer_id varchar(100),name varchar(180) NOT NULL,email varchar(254),phone varchar(40),document_type document_type_enum,document varchar(30),state_registration varchar(30),is_company boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`,
    );
    await q.query(
      `CREATE TABLE order_addresses(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,order_id uuid NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,type order_address_type_enum NOT NULL,recipient_name varchar(180) NOT NULL,street varchar(180) NOT NULL,number varchar(40) NOT NULL,complement varchar(120),district varchar(120),city varchar(120) NOT NULL,state varchar(80) NOT NULL,postal_code varchar(20) NOT NULL,country_code varchar(2) NOT NULL,reference varchar(250),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,order_id,type))`,
    );
    await q.query(
      `CREATE TABLE order_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,order_id uuid NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,product_id uuid REFERENCES products(id) ON DELETE RESTRICT,product_marketplace_link_id uuid REFERENCES product_marketplace_links(id) ON DELETE RESTRICT,marketplace_listing_id uuid REFERENCES marketplace_listings(id) ON DELETE RESTRICT,external_item_id varchar(100),external_variation_id varchar(100),external_sku varchar(160),sku_snapshot varchar(160) NOT NULL,name_snapshot varchar(240) NOT NULL,description_snapshot text,unit_of_measure_snapshot varchar(20) NOT NULL,quantity numeric(15,3) NOT NULL CHECK(quantity>0),unit_price numeric(15,2) NOT NULL CHECK(unit_price>=0),gross_amount numeric(15,2) NOT NULL CHECK(gross_amount>=0),discount_amount numeric(15,2) NOT NULL CHECK(discount_amount>=0),commission_amount numeric(15,2),shipping_allocation_amount numeric(15,2),net_amount numeric(15,2) NOT NULL CHECK(net_amount>=0),currency varchar(3) NOT NULL,status varchar(60),ncm_snapshot varchar(8),cest_snapshot varchar(7),cfop_snapshot varchar(4),merchandise_origin_snapshot varchar(30),tax_unit_snapshot varchar(20),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`,
    );
    await q.query(
      `CREATE INDEX idx_order_items_order ON order_items(company_id,order_id); CREATE INDEX idx_order_items_sku ON order_items(company_id,sku_snapshot)`,
    );
    await q.query(
      `CREATE TABLE order_payments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,order_id uuid NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,external_payment_id varchar(100),method payment_method_enum NOT NULL,method_detail varchar(100),status payment_status_enum NOT NULL,amount numeric(15,2) NOT NULL CHECK(amount>=0),installments integer CHECK(installments>0),authorization_code varchar(100),paid_at timestamptz,refunded_at timestamptz,external_created_at timestamptz,external_updated_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now()); CREATE UNIQUE INDEX uq_order_payment_external ON order_payments(company_id,order_id,external_payment_id) WHERE external_payment_id IS NOT NULL`,
    );
    await q.query(
      `CREATE TABLE order_shipments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,order_id uuid NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,external_shipment_id varchar(100),status shipping_status_enum NOT NULL,substatus varchar(80),logistic_type varchar(80),shipping_mode varchar(80),carrier_name varchar(120),tracking_number varchar(120),tracking_url text,shipping_amount numeric(15,2) NOT NULL CHECK(shipping_amount>=0),estimated_delivery_at timestamptz,ready_to_ship_at timestamptz,shipped_at timestamptz,delivered_at timestamptz,returned_at timestamptz,external_updated_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now()); CREATE UNIQUE INDEX uq_order_shipment_external ON order_shipments(company_id,order_id,external_shipment_id) WHERE external_shipment_id IS NOT NULL`,
    );
    await q.query(
      `CREATE TABLE order_fiscal_data(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,order_id uuid NOT NULL UNIQUE REFERENCES orders(id) ON DELETE RESTRICT,customer_document varchar(30),customer_state_registration varchar(30),fiscal_name varchar(180) NOT NULL,fiscal_email varchar(254),operation_nature varchar(180),default_cfop varchar(4),fiscal_status fiscal_status_enum NOT NULL,invoice_id uuid,invoice_access_key varchar(44),invoice_number varchar(30),invoice_series varchar(10),issued_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`,
    );
    await q.query(
      `CREATE TABLE order_issues(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,order_id uuid NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,order_item_id uuid REFERENCES order_items(id) ON DELETE RESTRICT,code order_issue_code_enum NOT NULL,severity order_issue_severity_enum NOT NULL,message varchar(500) NOT NULL,status order_issue_status_enum NOT NULL,resolution_note varchar(500),resolved_at timestamptz,resolved_by_user_id uuid REFERENCES users(id) ON DELETE RESTRICT,created_at timestamptz NOT NULL DEFAULT now()); CREATE INDEX idx_order_issues_open ON order_issues(company_id,order_id,status)`,
    );
    await q.query(
      `CREATE TABLE order_status_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,order_id uuid NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,previous_order_status order_status_enum,new_order_status order_status_enum NOT NULL,previous_payment_status payment_status_enum,new_payment_status payment_status_enum,previous_shipping_status shipping_status_enum,new_shipping_status shipping_status_enum,previous_fiscal_status fiscal_status_enum,new_fiscal_status fiscal_status_enum,source order_history_source_enum NOT NULL,external_event_id varchar(120),changed_by_user_id uuid REFERENCES users(id) ON DELETE RESTRICT,reason varchar(500),metadata jsonb,occurred_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now()); CREATE UNIQUE INDEX uq_order_history_event ON order_status_history(company_id,order_id,external_event_id) WHERE external_event_id IS NOT NULL; CREATE INDEX idx_order_history_order ON order_status_history(company_id,order_id,occurred_at DESC)`,
    );
  }
  async down(q: QueryRunner): Promise<void> {
    await q.query(
      `DROP TABLE order_status_history; DROP TABLE order_issues; DROP TABLE order_fiscal_data; DROP TABLE order_shipments; DROP TABLE order_payments; DROP TABLE order_items; DROP TABLE order_addresses; DROP TABLE order_customers; DROP TABLE orders; DROP TABLE company_order_sequences; DROP TYPE order_history_source_enum; DROP TYPE order_issue_status_enum; DROP TYPE order_issue_severity_enum; DROP TYPE order_issue_code_enum; DROP TYPE payment_method_enum; DROP TYPE order_address_type_enum; DROP TYPE document_type_enum; DROP TYPE commission_status_enum; DROP TYPE fiscal_status_enum; DROP TYPE shipping_status_enum; DROP TYPE payment_status_enum; DROP TYPE order_status_enum; DROP TYPE order_source_enum`,
    );
  }
}
